IF NOT EXISTS (
    SELECT * FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_NAME = 'Stacks'
)
BEGIN
    CREATE TABLE Stacks (
        Id INT IDENTITY(1, 1) PRIMARY KEY,
        Name NVARCHAR(50) NOT NULL UNIQUE
    );
END;

IF NOT EXISTS (
    SELECT * FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_NAME = 'Flashcards'
)
BEGIN
    CREATE TABLE Flashcards (
        Id INT IDENTITY(1, 1) PRIMARY KEY,
        StackId INT,
        Front NVARCHAR(50) NOT NULL,
        Back NVARCHAR(50) NOT NULL,
        FOREIGN KEY (StackId) REFERENCES Stacks(Id)
        ON DELETE CASCADE
    );
END;

IF NOT EXISTS (
    SELECT * FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_NAME = 'StudySessions'
)
BEGIN
CREATE TABLE StudySessions (
    Id INT IDENTITY(1, 1) PRIMARY KEY,
    StackId INT,
    Date DATETIME NOT NULL,
    Score INT NOT NULL,
    FOREIGN KEY (StackId) REFERENCES Stacks(Id)
    ON DELETE CASCADE
);
END;