//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flashcards {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlScripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlScripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Flashcards.SqlScripts", typeof(SqlScripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Flashcards (StackId, Front, Back)
        ///VALUES
        ///(@StackId, @Front, @Back).
        /// </summary>
        internal static string AddFlashcard {
            get {
                return ResourceManager.GetString("AddFlashcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Stacks (Name)
        ///VALUES
        ///(@Name).
        /// </summary>
        internal static string AddStack {
            get {
                return ResourceManager.GetString("AddStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO StudySessions (StackId, Date, Score)
        ///VALUES
        ///(@StackId, @Date, @Score).
        /// </summary>
        internal static string AddStudySession {
            get {
                return ResourceManager.GetString("AddStudySession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF NOT EXISTS (
        /// SELECT * FROM sys.databases WHERE name = &apos;Flashcards&apos;
        ///)
        ///BEGIN
        /// CREATE DATABASE Flashcards;
        ///END;.
        /// </summary>
        internal static string CreateDatabase {
            get {
                return ResourceManager.GetString("CreateDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF NOT EXISTS (
        ///    SELECT * FROM INFORMATION_SCHEMA.TABLES
        ///    WHERE TABLE_NAME = &apos;Stacks&apos;
        ///)
        ///BEGIN
        ///    CREATE TABLE Stacks (
        ///        Id INT IDENTITY(1, 1) PRIMARY KEY,
        ///        Name NVARCHAR(50) NOT NULL UNIQUE
        ///    );
        ///END;
        ///
        ///IF NOT EXISTS (
        ///    SELECT * FROM INFORMATION_SCHEMA.TABLES
        ///    WHERE TABLE_NAME = &apos;Flashcards&apos;
        ///)
        ///BEGIN
        ///    CREATE TABLE Flashcards (
        ///        Id INT IDENTITY(1, 1) PRIMARY KEY,
        ///        StackId INT,
        ///        Front NVARCHAR(50) NOT NULL,
        ///        Back NVARCHAR(50) NOT NUL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateTables {
            get {
                return ResourceManager.GetString("CreateTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM Flashcards
        ///WHERE Id = @Id.
        /// </summary>
        internal static string DeleteFlashcard {
            get {
                return ResourceManager.GetString("DeleteFlashcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM Flashcards
        ///WHERE Id = @Id AND StackId = @StackId.
        /// </summary>
        internal static string DeleteFlashcardFromStack {
            get {
                return ResourceManager.GetString("DeleteFlashcardFromStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM Stacks
        ///WHERE Id = @Id.
        /// </summary>
        internal static string DeleteStack {
            get {
                return ResourceManager.GetString("DeleteStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM Flashcards.
        /// </summary>
        internal static string GetFlashcards {
            get {
                return ResourceManager.GetString("GetFlashcards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM Flashcards
        ///WHERE StackId = @StackId.
        /// </summary>
        internal static string GetFlashcardsByStackId {
            get {
                return ResourceManager.GetString("GetFlashcardsByStackId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COUNT(Id)
        ///FROM Flashcards
        ///WHERE StackId = @StackId.
        /// </summary>
        internal static string GetFlashcardsCountInStack {
            get {
                return ResourceManager.GetString("GetFlashcardsCountInStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    Name AS StackName,
        ///    ISNULL([January], 0) AS JanuaryAverageScore,
        ///    ISNULL([February], 0) AS FebruaryAverageScore,
        ///    ISNULL([March], 0) AS MarchAverageScore,
        ///    ISNULL([April], 0) AS AprilAverageScore,
        ///    ISNULL([May], 0) AS MayAverageScore,
        ///    ISNULL([June], 0) AS JuneAverageScore,
        ///    ISNULL([July], 0) AS JulyAverageScore,
        ///    ISNULL([August], 0) AS AugustAverageScore,
        ///    ISNULL([September], 0) AS SeptemberAverageScore,
        ///    ISNULL([October], 0) AS OctoberAverageScore,
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetMonthlyStudySessionAverageScoreReport {
            get {
                return ResourceManager.GetString("GetMonthlyStudySessionAverageScoreReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    Name AS StackName,
        ///    ISNULL([January], 0) AS JanuaryNumber,
        ///    ISNULL([February], 0) AS FebruaryNumber,
        ///    ISNULL([March], 0) AS MarchNumber,
        ///    ISNULL([April], 0) AS AprilNumber,
        ///    ISNULL([May], 0) AS MayNumber,
        ///    ISNULL([June], 0) AS JuneNumber,
        ///    ISNULL([July], 0) AS JulyNumber,
        ///    ISNULL([August], 0) AS AugustNumber,
        ///    ISNULL([September], 0) AS SeptemberNumber,
        ///    ISNULL([October], 0) AS OctoberNumber,
        ///    ISNULL([November], 0) AS NovemberNumber,
        ///    ISNULL([Decemb [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetMonthlyStudySessionReport {
            get {
                return ResourceManager.GetString("GetMonthlyStudySessionReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM Stacks
        ///WHERE Name = @Name.
        /// </summary>
        internal static string GetStack {
            get {
                return ResourceManager.GetString("GetStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM Stacks.
        /// </summary>
        internal static string GetStacks {
            get {
                return ResourceManager.GetString("GetStacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM StudySessions.
        /// </summary>
        internal static string GetStudySessions {
            get {
                return ResourceManager.GetString("GetStudySessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF EXISTS (
        ///    SELECT 1 FROM StudySessions
        ///)
        ///BEGIN
        ///    SELECT 1;
        ///END
        ///ELSE
        ///BEGIN
        ///    SELECT 0;
        ///END;.
        /// </summary>
        internal static string HasStudySession {
            get {
                return ResourceManager.GetString("HasStudySession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF NOT EXISTS (
        ///	SELECT 1 FROM Flashcards
        ///)
        ///BEGIN
        ///	INSERT INTO Flashcards (StackId, Front, Back) VALUES
        ///	(1, &apos;Hola&apos;, &apos;Hello&apos;),
        ///	(1, &apos;¿Cómo estás?&apos;, &apos;How are you?&apos;),
        ///	(1, &apos;Gracias&apos;, &apos;Thank you&apos;),
        ///	(2, &apos;Hallo&apos;, &apos;Hello&apos;),
        ///	(2, &apos;Wie geht es dir?&apos;, &apos;How are you?&apos;),
        ///	(2, &apos;Danke&apos;, &apos;Thank you&apos;),
        ///	(3, &apos;Dzień dobry&apos;, &apos;Good morning&apos;),
        ///	(3, &apos;Do widzenia&apos;, &apos;Goodbye&apos;),
        ///	(3, &apos;Proszę&apos;, &apos;Please&apos;)
        ///END;.
        /// </summary>
        internal static string SeedFlashcards {
            get {
                return ResourceManager.GetString("SeedFlashcards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF NOT EXISTS (
        ///    SELECT 1 FROM Stacks
        ///)
        ///BEGIN
        ///    INSERT INTO Stacks (Name) VALUES
        ///    (&apos;Spanish&apos;),
        ///    (&apos;German&apos;),
        ///    (&apos;Polish&apos;);
        ///END;.
        /// </summary>
        internal static string SeedStacks {
            get {
                return ResourceManager.GetString("SeedStacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF EXISTS (
        ///    SELECT 1 FROM Stacks WHERE Name = @Name
        ///)
        ///BEGIN
        ///    SELECT 1;
        ///END
        ///ELSE
        ///BEGIN
        ///    SELECT 0;
        ///END;.
        /// </summary>
        internal static string StackExistsWithName {
            get {
                return ResourceManager.GetString("StackExistsWithName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Flashcards
        ///SET Front = @Front, Back = @Back
        ///WHERE Id = @Id.
        /// </summary>
        internal static string UpdateFlashcard {
            get {
                return ResourceManager.GetString("UpdateFlashcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Flashcards
        ///SET Front = @Front, Back = @Back
        ///WHERE Id = @Id AND StackId = @StackId.
        /// </summary>
        internal static string UpdateFlashcardInStack {
            get {
                return ResourceManager.GetString("UpdateFlashcardInStack", resourceCulture);
            }
        }
    }
}
