name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env:
  DOTNET_CORE_VERSION: 9.0.x
  WORKING_DIRECTORY: Flashcards
  CONFIGURATION: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Install dependencies
      run: dotnet restore ${{ env.WORKING_DIRECTORY }}
    - name: Build
      run: dotnet build ${{ env.WORKING_DIRECTORY }} --configuration ${{ env.CONFIGURATION }} --no-restore
    - name: Test
      run: dotnet test Flashcards.sln --configuration ${{ env.CONFIGURATION }} --no-build